'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class rxviewserialnumberdata

    '''<summary>
    '''rxviewserialnumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rxviewserialnumber As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''serial_number control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents serial_number As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnGet control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnGet As Global.System.Web.UI.HtmlControls.HtmlInputSubmit

    '''<summary>
    '''MyGridView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MyGridView As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''GetMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GetMessage As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''MyGridViewDistSales control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MyGridViewDistSales As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''MyGridViewWarranty control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MyGridViewWarranty As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''MyGridViewConsSales control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MyGridViewConsSales As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''btnExcelDistSales control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnExcelDistSales As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnExcelWarranty control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnExcelWarranty As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnExcelConsSales control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnExcelConsSales As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnReturn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnReturn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''gridcountDistSales control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gridcountDistSales As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''gridcountWarranty control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gridcountWarranty As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''gridcountConsSales control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gridcountConsSales As Global.System.Web.UI.HtmlControls.HtmlInputHidden
End Class
