<%@ Page Language="vb" AutoEventWireup="true" CodeBehind="wsapplicationareamaint.aspx.vb" Inherits="RexairWebSecurity.wsapplicationarea" EnableSessionState = "True"%>

<!--#include virtual="/ForceSSL.inc"-->

<!DOCTYPE html >

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title>WS Application Area Maintenance</title>
    <link rel="stylesheet" href="../Content/wsSite.css"/>
     <script src="../Scripts/JavaScript.js" type="text/javascript"></script>
</head>

<body oncontextmenu="return false">

  <form id="wsappareamaint" runat="server"  defaultbutton="btnAdd" defaultfocus="group_id">
      <div id="container">
          <div class="row">
               <div class="column left" > <h1>Application Area Maintenance</h1>
               </div>
               <div class="column right" > <img src="../images/logo_small.png" alt="Rexair LLC"  width="200" height="100" />
               </div>
         </div>

        <div id="frame">
	
    <table width:"30%" class="font8veranda">
            <tr>
              <td class="aligntext">
			      <asp:HyperLink runat="server" Text="Application ID:" NavigateURL="wsapplicationmastermaint.aspx" Target="_blank"/>
              </td>
              <td>
	              <input type="button" id="btnSearch" onclick='pickApplication("getapplication_id");' value="S" runat="server"/>
              </td>
              <td>
                <asp:TextBox ID="getapplication_id" AutoPostBack="false" ReadOnly="false" runat="server" MaxLength="20" Width="168px" CssClass="requiredfield" ToolTip="Enter a valid application ID." TabIndex="1"></asp:TextBox> 
              </td>
		      <td>
                <asp:TextBox ID="getapplication_name" AutoPostBack="false" ReadOnly="true" runat="server" MaxLength="40" Width="300" BackColor="#CCCCCC"></asp:TextBox> 
              </td>
			  <td>
			     <input type="submit" id="btnGet" OnServerClick="GetApplication_Click" value="Get" runat="server" tabindex="2"/>
			  </td>  
             </tr>
             <tr>
              <td colspan="4" class="paddingtop15; textaligncenter">
                <span id="GetMessage" EnableViewState="false" class="font11arial" runat="server"/>
              </td>
            </tr>
    </table>
    <hr class="hrheight2"/>
	<br/>
    <table width:"30%" >
	<tr>
        <td >
          <ASP:GridView id="MyGridView" runat="server"
            Width="700"
            BackColor="#CCCCCC"
            BorderColor="black"
            ShowFooter="false"
            CellPadding="3"
            CellSpacing="0"
            Font-Names="Verdana"
            Font-Size="8pt"
            HeaderStyle-BackColor="#aaaadd"
            EnableViewState="true"
			OnRowCancelingEdit = "gv_RowCancelingEdit" 
			OnRowDeleting="gv_RowDeleting" 
			OnRowDeleted="gv_RowDeleted"
			OnRowUpdating="gv_RowUpdating" 
			OnRowUpdated="gv_RowUpdated"
			OnRowEditing="gv_RowEditing" 
			OnPageIndexChanged = "gv_PageIndexChanged" 
			OnPageIndexChanging = "gv_PageIndexChanging" 
			OnRowDataBound = "gv_RowDataBound"
			OnRowCreated = "gv_RowCreated"
			OnSorting="gv_Sorting" 
			OnPreRender="gv_PreRender"
			DataKeyNames="application_id"
			AutoGenerateColumns="false"
			AutoGenerateEditButton = "true"
			AutoGenerateDeleteButton = "true" 
			PageSize="200"
			AllowSorting="True"
			AllowPaging="True">
				
		    <FooterStyle forecolor="Black" backcolor="#CCCCCC"></FooterStyle>
            <HeaderStyle font-bold="True" forecolor="White" backcolor="#2876CD"></HeaderStyle>
            <PagerStyle horizontalalign="Right" forecolor="Black" backcolor="#999999" Font-Names="Verdana" Font-Size="Small"></PagerStyle>
            <PagerSettings Mode="NumericFirstLast" Position="Top"/>
			<EditRowStyle BackColor="#E6E8FA" />
            <SelectedRowStyle BackColor="#C5BBAF" Font-Bold="True" ForeColor="#333333" />
            <EmptyDataTemplate>
               <asp:Label ID="Label1" runat="server">
                   There is no data to display in this view or enter a valid Application ID and click Get.
               </asp:Label>
            </EmptyDataTemplate>
            					
			<Columns>
			   <asp:BoundField HeaderText="Application ID" DataField="application_id" ItemStyle-Width="150px" ReadOnly="true"/> 
			   <asp:BoundField HeaderText="Area ID" DataField="area_id" ItemStyle-Width="150px" ReadOnly="true" SortExpression="user_id"/>

               <asp:TemplateField HeaderText="Form Type">
		         <ItemTemplate>
                   <asp:CheckBox ID="TypeFormCheckBox" Enabled="False"
                      Checked='<%# DataBinder.Eval(Container.DataItem, "type_form") %>'
                      runat="server" />
                 </ItemTemplate>
			   
                 <EditItemTemplate>
                   <asp:CheckBox ID="edit_TypeFormCheckBox" Enabled="True"
                      Checked='<%# DataBinder.Eval(Container.DataItem, "type_form") %>'
                      Runat="server" />
                 </EditItemTemplate>
               </asp:TemplateField>

               <asp:TemplateField HeaderText="Menu Type">
		         <ItemTemplate>
                   <asp:CheckBox ID="TypeMenuCheckBox" Enabled="False"
                      Checked='<%# DataBinder.Eval(Container.DataItem, "type_menu") %>'
                      runat="server" />
                 </ItemTemplate>
			   
                 <EditItemTemplate>
                   <asp:CheckBox ID="edit_TypeMenuCheckBox" Enabled="True"
                      Checked='<%# DataBinder.Eval(Container.DataItem, "type_menu") %>'
                      Runat="server" />
                 </EditItemTemplate>
               </asp:TemplateField>

               <asp:TemplateField HeaderText="Report Type">
		         <ItemTemplate>
                   <asp:CheckBox ID="TypeReportCheckBox" Enabled="False"
                      Checked='<%# DataBinder.Eval(Container.DataItem, "type_report") %>'
                      runat="server" />
                 </ItemTemplate>
			   
                 <EditItemTemplate>
                   <asp:CheckBox ID="edit_TypeReportCheckBox" Enabled="True"
                      Checked='<%# DataBinder.Eval(Container.DataItem, "type_report") %>'
                      Runat="server" />
                 </EditItemTemplate>
               </asp:TemplateField>
	
	           <asp:TemplateField HeaderText="Inactive">
		         <ItemTemplate>
                   <asp:CheckBox ID="InactiveCheckBox" Enabled="False"
                      Checked='<%# DataBinder.Eval(Container.DataItem, "inactive") %>'
                      runat="server" />
                 </ItemTemplate>
			   
                 <EditItemTemplate>
                   <asp:CheckBox ID="edit_InactiveCheckBox" Enabled="True"
                      Checked='<%# DataBinder.Eval(Container.DataItem, "inactive") %>'
                      Runat="server" />
                 </EditItemTemplate>
               </asp:TemplateField>

			   <asp:TemplateField HeaderText="Lst Mod Dt" ItemStyle-Width="150px" Visible="false">
                 <ItemTemplate>
                   <asp:Label id="moddate" runat="server" Text='<%# DataBinder.Eval(Container, "DataItem.modification_date") %>' > 
                   </asp:Label>
                 </ItemTemplate>
               </asp:TemplateField>
			
			</Columns>
		  </ASP:GridView>
		</td>  
		  
        <td valign="top">
          <div class="frame">
          <table class="font8veranda">
            <tr>
              <td colspan="2" class="font10veranda">Add a New Application Area:</td>
            </tr>
            <tr>
              <td class="aligntext"><strong>Application ID: </strong></td>
              <td>
                <asp:TextBox ID="application_id" AutoPostBack="false" ReadOnly="true" runat="server" MaxLength="20" Width="150" BackColor="#CCCCCC"></asp:TextBox> 
              </td>
             </tr>
             <tr>
              <td class="aligntext"><strong>Area ID: </strong></td>
              <td>
   	             <asp:Textbox id="area_id" AutoPostBack="true" runat="server" MaxLength="50" Width="200" CssClass="requiredfield" ToolTip="Enter an Area ID." TabIndex="3"/>
             </td>
             </tr>
   			<tr>
	           <td class="aligntext"><strong>Form: </strong></td>
	           <td>
                 <asp:CheckBox ID="type_form" AutoPostBack="false" Enabled="true" runat="server" ToolTip="Check of the Area is a Form Type." TabIndex="4"></asp:CheckBox> 
               </td>
            </tr> 

   			<tr>
	           <td class="aligntext"><strong>Menu: </strong></td>
	           <td>
                 <asp:CheckBox ID="type_menu" AutoPostBack="false" Enabled="true" runat="server" ToolTip="Check of the Area is a Menu Type." TabIndex="5"></asp:CheckBox> 
               </td>
            </tr> 

   			<tr>
	           <td class="aligntext"><strong>Report: </strong></td>
	           <td>
                 <asp:CheckBox ID="type_report" AutoPostBack="false" Enabled="true" runat="server" ToolTip="Check of the Area is a Report Type." TabIndex="6"></asp:CheckBox> 
               </td>
            </tr> 

  			<tr>
	           <td class="aligntext"><strong>Inactive: </strong></td>
	           <td>
                 <asp:CheckBox ID="inactive" AutoPostBack="false" Enabled="true" runat="server" ToolTip="Enter the status of the Application Area." TabIndex="7"></asp:CheckBox> 
               </td>
            </tr> 
			 
             <tr>
              <td></td>
              <td class="paddingtop15">
                <asp:Button id="btnAdd" Text="Add" OnClick="AddApplicationArea_Click" runat="server" ToolTip="Click to save the Application Area. ALT+D" AccessKey="A" TabIndex="8"/>
                <asp:Button Text="Clear" OnClick="PageReset_Click" runat="server" ToolTip="Click to reset the window. ALT+C" AccessKey="C" TabIndex="9"/>

		      </td>
             </tr>
 	         <tr>
             <td colspan="2" class="paddingtop15; textaligncenter">
              <span id="AddMessage" EnableViewState="false" class="font11arial" runat="server"/>
             </td>
            </tr>	
           </table>
		  </div>
        </td>
	    </tr>
        <tr>
           <td colspan="2" class="paddingtop15; textalignleft">
              <span id="Message" EnableViewState="false" class="font11arial" runat="server"/>
           </td>
        </tr>	
	</table>
	<table width="100%" class="textalignright">
	    <tr>
		   <td>
                <asp:TextBox ID="sort_id" AutoPostBack="false" ReadOnly="true" runat="server" MaxLength="40" Width="40" Visible="false"></asp:TextBox> 
		   </td>
		</tr>
		<tr>
           <td>
               <asp:Button id="btnPrint" Text="Print" OnClick="PrintData" runat="server" ToolTip="Click to Print the Data. ALT+P" AccessKey="P" TabIndex="10"/>
	           <asp:Button id="btnReturn" Text="Return to Main Menu" OnClick="ReturnToMainMenu" runat="server" ToolTip="Click to return to the Web Security Main Menu. ALT+R" AccessKey="R" TabIndex="11"/>
		   </td>
		</tr>
	</table>
    </div>
 </div>
  </form>
 
</body>
</html>
