'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class wsgroupmastersearch

    '''<summary>
    '''wsusermastersearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents wsusermastersearch As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''GroupSelect control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GroupSelect As Global.System.Web.UI.WebControls.ListBox

    '''<summary>
    '''getgroupid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents getgroupid As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''getgroupname control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents getgroupname As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''btnGet control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnGet As Global.System.Web.UI.HtmlControls.HtmlInputSubmit

    '''<summary>
    '''btnClose control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnClose As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''Message control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Message As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''MyGridView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MyGridView As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''getsource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents getsource As Global.System.Web.UI.HtmlControls.HtmlInputHidden
End Class
