<%@ Page Language="vb" AutoEventWireup="true" CodeBehind="wsgroupapplicationarea.aspx.vb" Inherits="RexairWebSecurity.wsgroupapplicationarea" EnableSessionState = "True"%>

<!--#include virtual="/ForceSSL.inc"-->

<!DOCTYPE html >

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title>WS Group Application Area Maintenance</title>
    <link rel="stylesheet" href="../Content/wsSite.css"/>
     <script src="../Scripts/JavaScript.js" type="text/javascript"></script>
</head>

<body class="font8veranda" oncontextmenu="return false">

   <form id="wsuserareagroupmaint" runat="server">
     <div id="container">
          <div class="row">
               <div class="column left" > <h1>Group Application Area Maintenance</h1>
               </div>
               <div class="column right" > <img src="../images/logo_small.png" alt="Rexair LLC"  width="200" height="100" />
               </div>
         </div>

        <div id="frame">
	    
   <table width="30%" class="font8veranda">
           <tr>
 			  <td class="aligntext">
			     <asp:HyperLink runat="server" Text="Group ID:" NavigateURL="wsgroupapplicationareamaint.aspx" Target="_blank" TabIndex="0"/>
			  </td>
              <td>
	             <input type="button" id="btnSearch" onclick='javascript:pickGroup("getgroup_id");' value="S" runat="server" tabindex="0"/>
              </td>
              <td>
 	             <asp:Textbox id="getgroup_id" AutoPostBack="true" OnTextChanged="ReturnGroup_Click" runat="server" MaxLength="20" Width="200" CssClass="requiredfield" ToolTip="Enter a valid Group ID." TabIndex="1"/>
              </td>
  	          <td>
                <asp:TextBox ID="getgroup_name" AutoPostBack="false" ReadOnly="true" runat="server" MaxLength="100" Width="300" BackColor="#CCCCCC"></asp:TextBox> 
              </td>
              <td>
			     <input type="button" id="btnGet" onServerClick="ReturnGroup_Click" value="" runat="server" disabled="disabled" class="buttonvisbilityhidden" tabindex="0"/>
	          </td>
			  </tr>
              <tr>
 			  <td class="aligntext">
			     <asp:HyperLink runat="server" Text="Application ID:" NavigateURL="wsapplicationmastermaint.aspx" Target="_blank" TabIndex="0"/>
			  </td>
              <td>
	             <input type="button" id="btnApplicationAreaSearch" onclick='javascript: pickApplicationAreaSubmit("getapplication_id");' value="S" runat="server" tabindex="0" />
              </td>
              <td>
                 <asp:TextBox ID="getapplication_id" AutoPostBack="false" ReadOnly="false" runat="server" MaxLength="20" Width="200" CssClass="requiredfield" ToolTip="Enter a valid Application ID." TabIndex="2"></asp:TextBox> 
              </td>
			  <td>
                <asp:TextBox ID="getapplication_name" AutoPostBack="false" ReadOnly="true" runat="server" MaxLength="40" Width="300" BackColor="#CCCCCC"></asp:TextBox> 
              </td>
			  <td>
                <asp:TextBox ID="getarea_id" AutoPostBack="false" ReadOnly="true" runat="server" MaxLength="20" Width="200" BackColor="#CCCCCC"></asp:TextBox> 
              </td>
			  <td>
			     <input type="submit" id="btnSubmit" OnServerClick="GetGroupApplicationArea_Click" value="Get" runat="server" tabindex="3"/>
			  </td>  
             </tr>
             <tr>
              <td colspan="5" class="paddingtop15; textalignleft">
                <span id="GetMessage" EnableViewState="false" class="font11arial" runat="server"/>
              </td>
            </tr>
     </table>
    <hr class="hrheight2"/>
	<br/>
    <table width="30%" >
	<tr>
        <td >
          <ASP:GridView id="MyGridView" runat="server"
            Width="600"
            BackColor="#CCCCCC"
            BorderColor="black"
            ShowFooter="false"
            CellPadding="3"
            CellSpacing="0"
            Font-Names="Verdana"
            Font-Size="8pt"
            HeaderStyle-BackColor="#aaaadd"
            EnableViewState="true"
			OnRowCancelingEdit = "gv_RowCancelingEdit" 
			OnRowDeleting="gv_RowDeleting" 
			OnRowDeleted="gv_RowDeleted"
			OnRowUpdating="gv_RowUpdating" 
			OnRowUpdated="gv_RowUpdated"
			OnRowEditing="gv_RowEditing" 
			OnPageIndexChanged = "gv_PageIndexChanged" 
			OnPageIndexChanging = "gv_PageIndexChanging" 
			OnRowDataBound = "gv_RowDataBound"
			OnRowCreated = "gv_RowCreated"
			OnSorting="gv_Sorting" 
			OnPreRender="gv_PreRender"
			AutoGenerateEditButton = "true"
			AutoGenerateDeleteButton = "true" 
			DataKeyNames="group_id"
			AutoGenerateColumns="false"
			PageSize="200"
			AllowSorting="True"
			AllowPaging="True">
				
		    <FooterStyle forecolor="Black" backcolor="#CCCCCC"></FooterStyle>
            <HeaderStyle font-bold="True" forecolor="White" backcolor="#2876CD"></HeaderStyle>
            <PagerStyle horizontalalign="Right" forecolor="Black" backcolor="#999999" Font-Names="Verdana" Font-Size="Small"></PagerStyle>
            <PagerSettings Mode="NumericFirstLast" Position="Top"/>
			<EditRowStyle BackColor="#E6E8FA" />
            <SelectedRowStyle BackColor="#C5BBAF" Font-Bold="True" ForeColor="#333333" />
            <EmptyDataTemplate>
               <asp:Label ID="Label1" runat="server">
                   There is no data to display in this view or enter a valid Group and Application / Area then click Get.
               </asp:Label>
            </EmptyDataTemplate>
            					
			<Columns>
			   <asp:BoundField HeaderText="Group ID" DataField="group_id" ItemStyle-Width="500px" ReadOnly="true" HeaderStyle-HorizontalAlign="Left" ItemStyle-HorizontalAlign="Left"/> 
			   <asp:BoundField HeaderText="Application ID" DataField="application_id" ReadOnly="true" ItemStyle-Width="500px" HeaderStyle-HorizontalAlign="Left" ItemStyle-HorizontalAlign="Left"/>
			   <asp:BoundField HeaderText="Area ID" DataField="area_id" ReadOnly="true" SortExpression="area_id" ItemStyle-Width="600px" HeaderStyle-HorizontalAlign="Left" ItemStyle-HorizontalAlign="Left"/>
			   
	           <asp:TemplateField HeaderText="Create Permission" HeaderStyle-HorizontalAlign="Left" ItemStyle-HorizontalAlign="Left">
		         <ItemTemplate>
                   <asp:CheckBox ID="PermissionCreateCheckBox" Enabled="False"
                      Checked='<%# DataBinder.Eval(Container.DataItem, "permission_create") %>'
                      runat="server" />
                 </ItemTemplate>
			   
                 <EditItemTemplate>
                   <asp:CheckBox ID="edit_PermissionCreateCheckBox" Enabled="True"
                      Checked='<%# DataBinder.Eval(Container.DataItem, "permission_create") %>'
                      Runat="server" />
                 </EditItemTemplate>
               </asp:TemplateField>

               <asp:TemplateField HeaderText="Read Permission" HeaderStyle-HorizontalAlign="Left" ItemStyle-HorizontalAlign="Left">
		         <ItemTemplate>
                   <asp:CheckBox ID="PermissionReadCheckBox" Enabled="False"
                      Checked='<%# DataBinder.Eval(Container.DataItem, "permission_read") %>'
                      runat="server" />
                 </ItemTemplate>
			   
                 <EditItemTemplate>
                   <asp:CheckBox ID="edit_PermissionReadCheckBox" Enabled="True"
                      Checked='<%# DataBinder.Eval(Container.DataItem, "permission_read") %>'
                      Runat="server" />
                 </EditItemTemplate>
               </asp:TemplateField>

               <asp:TemplateField HeaderText="Update Permission" HeaderStyle-HorizontalAlign="Left" ItemStyle-HorizontalAlign="Left">
		         <ItemTemplate>
                   <asp:CheckBox ID="PermissionUpdateCheckBox" Enabled="False"
                      Checked='<%# DataBinder.Eval(Container.DataItem, "permission_update") %>'
                      runat="server" />
                 </ItemTemplate>
			   
                 <EditItemTemplate>
                   <asp:CheckBox ID="edit_PermissionUpdateCheckBox" Enabled="True"
                      Checked='<%# DataBinder.Eval(Container.DataItem, "permission_update") %>'
                      Runat="server" />
                 </EditItemTemplate>
               </asp:TemplateField>

               <asp:TemplateField HeaderText="Delete Permission" HeaderStyle-HorizontalAlign="Left" ItemStyle-HorizontalAlign="Left">
		         <ItemTemplate>
                   <asp:CheckBox ID="PermissionDeleteCheckBox" Enabled="False"
                      Checked='<%# DataBinder.Eval(Container.DataItem, "permission_delete") %>'
                      runat="server" />
                 </ItemTemplate>
			   
                 <EditItemTemplate>
                   <asp:CheckBox ID="edit_PermissionDeleteCheckBox" Enabled="True"
                      Checked='<%# DataBinder.Eval(Container.DataItem, "permission_delete") %>'
                      Runat="server" />
                 </EditItemTemplate>
               </asp:TemplateField>

	           <asp:TemplateField HeaderText="Inactive" HeaderStyle-HorizontalAlign="Left" ItemStyle-HorizontalAlign="Left">
		         <ItemTemplate>
                   <asp:CheckBox ID="InactiveCheckBox" Enabled="False"
                      Checked='<%# Databinder.Eval(Container.DataItem, "inactive") %>'
                      runat="server" />
                 </ItemTemplate>
			   
                 <EditItemTemplate>
                   <asp:CheckBox ID="edit_InactiveCheckBox" Enabled="True"
                      Checked='<%# Databinder.Eval(Container.DataItem, "inactive") %>'
                      Runat="server" />
                 </EditItemTemplate>
               </asp:TemplateField>

			   <asp:TemplateField HeaderText="Lst Mod Dt" ItemStyle-Width="150px" Visible="false" HeaderStyle-HorizontalAlign="Left" ItemStyle-HorizontalAlign="Left">
                 <ItemTemplate>
                   <asp:Label id="moddate" runat="server" Text='<%# DataBinder.Eval(Container, "DataItem.modification_date") %>' > 
                   </asp:Label>
                 </ItemTemplate>
               </asp:TemplateField>
			
			</Columns>
		  </ASP:GridView>
		</td>  
		  
        <td valign="top">
          <div class="frame">
          <table class="font8veranda">
            <tr>
              <td colspan="2" class="font10veranda">Add a New Group Application Area:</td>
            </tr>
             <tr>
              <td class="aligntext"><strong>Group ID: </strong></td>
              <td>
                <asp:TextBox ID="group_id" AutoPostBack="false" ReadOnly="true" runat="server" MaxLength="20" Width="200" BackColor="#CCCCCC" TabIndex="0"></asp:TextBox> 
              </td>
            </tr>
             <tr>
              <td class="aligntext"><strong>Application ID: </strong></td>
              <td>
                <asp:TextBox ID="application_id" AutoPostBack="false" ReadOnly="true" runat="server" MaxLength="20" Width="200" BackColor="#CCCCCC" TabIndex="0"></asp:TextBox> 
              </td>
             </tr>
             <tr>
              <td class="aligntext"><strong>Area ID: </strong></td>
              <td>
                <asp:TextBox ID="area_id" AutoPostBack="false" ReadOnly="true" runat="server" MaxLength="20" Width="200" BackColor="#CCCCCC" TabIndex="0"></asp:TextBox> 
              </td>
             </tr>

		    <tr>
	           <td class="aligntext"><strong>Permission Create: </strong></td>
	           <td>
                 <asp:CheckBox ID="permission_create" AutoPostBack="false" Enabled="true" runat="server" ToolTip="Enter Create Permission." TabIndex="1"></asp:CheckBox> 
               </td>
            </tr> 

            <tr>
	           <td class="aligntext"><strong>Permission Read: </strong></td>
	           <td>
                 <asp:CheckBox ID="permission_read" AutoPostBack="false" Enabled="true" runat="server" ToolTip="Enter Read Permission." TabIndex="2"></asp:CheckBox> 
               </td>
            </tr> 

            <tr>
	           <td class="aligntext"><strong>Permission Update: </strong></td>
	           <td>
                 <asp:CheckBox ID="permission_update" AutoPostBack="false" Enabled="true" runat="server" ToolTip="Enter Update Permission." TabIndex="3"></asp:CheckBox> 
               </td>
            </tr> 

            <tr>
	           <td class="aligntext"><strong>Permission Delete: </strong></td>
	           <td>
                 <asp:CheckBox ID="permission_delete" AutoPostBack="false" Enabled="true" runat="server" ToolTip="Enter Deletee Permission." TabIndex="4"></asp:CheckBox> 
               </td>
            </tr> 


		    <tr>
	           <td class="aligntext"><strong>Inactive: </strong></td>
	           <td>
                 <asp:CheckBox ID="inactive" AutoPostBack="false" Enabled="true" runat="server" ToolTip="Enter the status of the Group Application Area." TabIndex="5"></asp:CheckBox> 
               </td>
            </tr> 
			 
             <tr>
              <td></td>
              <td class="paddingtop15">
                <asp:Button id="btnAdd" Text="Add" OnClick="AddGroupApplicationArea_Click" runat="server" ToolTip="Click to save the Group Application Area combination. ALT+D" AccessKey="D" TabIndex="6"/>
                <asp:Button Text="Clear" OnClick="PageReset_Click" runat="server" ToolTip="Click to reset the window. ALT+C" AccessKey="C" TabIndex="3"/>
		      </td>
             </tr>
 	         <tr>
             <td colspan="2" class="paddingtop15; textaligncenter">
              <span id="AddMessage" EnableViewState="false" class="font11arial" runat="server"/>
             </td>
            </tr>	
           </table>
		  </div>
        </td>
	    </tr>
        <tr>
           <td colspan="2" class="paddingtop15; textalignleft">
              <span id="Message" EnableViewState="false" class="font11arial" runat="server"/>
           </td>
        </tr>	
	</table>
	<table width="100%" class="textalignright">
	    <tr>
		   <td>
                <asp:TextBox ID="sort_id" AutoPostBack="false" ReadOnly="true" runat="server" MaxLength="40" Width="40" Visible="false"></asp:TextBox> 
		   </td>
		</tr>
		<tr>
           <td>
               <asp:Button id="btnPrint" Text="Print" OnClick="PrintData" runat="server" ToolTip="Click to Print the Data. ALT+P" AccessKey="P" TabIndex="7"/>
               <asp:Button id="btnReturn" Text="Return to Main Menu" OnClick="ReturnToMainMenu" runat="server" ToolTip="Click to return to the Web Security Main Menu. ALT+R" AccessKey="R" TabIndex="8"/>

		   </td>
		</tr>
	</table>
    </div>
    </div>
   </form>
  </body>
</html>
