<%@ Page Language="vb" AutoEventWireup="true" CodeBehind="wslocationmastermaint.aspx.vb" Inherits="RexairWebSecurity.locationmastermaint" EnableSessionState = "True" %>

<!--#include virtual="/ForceSSL.inc"-->

<!DOCTYPE html >

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title>WS Location Master Maintenance</title>
    <link rel="stylesheet" href="../Content/wsSite.css"/>
</head>

<body oncontextmenu="return false">

  <form id="wslocationmastermaint" runat="server"  defaultbutton="btnAdd" defaultfocus="location_id">
      <div id="container">
          <div class="row">
               <div class="column left" > <h1>Location Master Maintenance</h1>
               </div>
               <div class="column right" > <img src="../images/logo_small.png" alt="Rexair LLC"  width="200" height="100" />
               </div>
         </div>

        <div id="frame">
	
      <table class="table_input" >
        <tr>
            <td style="vertical-align:top;">
                 <asp:GridView ID="MyGridView" runat="server" 
                    Width="500"
                    AllowPaging="True" 
                    AllowSorting="True" 
                    AutoGenerateColumns="false" 
                    BackColor="#cccccc" 
                    BorderColor="black" 
                    CellPadding="3" 
                    CellSpacing="0" 
                    EnableViewState="true" 
                    Font-Names="Verdana" 
                    Font-Size="8pt" 
                    HeaderStyle-BackColor="#aaaadd" 
                    DataKeyNames="location_id"
			        AutoGenerateEditButton = "true"
			        AutoGenerateDeleteButton = "true" 
			        OnRowCancelingEdit = "gv_RowCancelingEdit" 
			        OnRowDeleting="gv_RowDeleting" 
			        OnRowDeleted="gv_RowDeleted"
			        OnRowUpdating="gv_RowUpdating" 
			        OnRowUpdated="gv_RowUpdated"
			        OnRowEditing="gv_RowEditing" 
			        OnPageIndexChanged = "gv_PageIndexChanged" 
			        OnPageIndexChanging = "gv_PageIndexChanging" 
			        OnRowDataBound = "gv_RowDataBound"
			        OnRowCreated = "gv_RowCreated"
			        OnSorting="gv_Sorting" 
			        OnPreRender="gv_PreRender"
			        PageSize="200" 
                    ShowFooter="false">
                    
		    <FooterStyle forecolor="Black" backcolor="#CCCCCC"></FooterStyle>
            <HeaderStyle font-bold="True" forecolor="White" backcolor="#2876CD"></HeaderStyle>
            <PagerStyle horizontalalign="Right" forecolor="Black" backcolor="#999999" 
                         Font-Names="Verdana" Font-Size="Small"></PagerStyle>
            <PagerSettings Mode="NumericFirstLast" Position="Top"/>
			<EditRowStyle BackColor="#E6E8FA" />
            <SelectedRowStyle BackColor="#C5BBAF" Font-Bold="True" ForeColor="#333333" />
            <EmptyDataTemplate>
               <asp:Label ID="Label1" runat="server">
                   There is no data to display in this view.
               </asp:Label>
            </EmptyDataTemplate>
            
                     <Columns>
                         <asp:BoundField DataField="location_id" HeaderText="Location ID" 
                            ItemStyle-Width="100px" ReadOnly="true" SortExpression="location_id" HeaderStyle-HorizontalAlign="Left">
                          <ItemStyle Width="100px"></ItemStyle>
                         </asp:BoundField>

			            <asp:TemplateField HeaderText="Location Name" HeaderStyle-HorizontalAlign="Left" ItemStyle-Width="200px" SortExpression="location_name">
                            <ItemTemplate>
                               <%#Eval("location_name")%>
                            </ItemTemplate> 
                            <EditItemTemplate>
                                <asp:TextBox ID="locationname" runat="server" Text='<%#Eval("location_name") %>'/>
                            </EditItemTemplate> 

                            <HeaderStyle HorizontalAlign="Left"></HeaderStyle>

                            <ItemStyle Width="200px"></ItemStyle>
                        </asp:TemplateField>                            
           
                       <asp:TemplateField HeaderText="Inactive" ItemStyle-Width="20px" SortExpression="inactive" ItemStyle-HorizontalAlign="center">
                            <ItemTemplate >
                                <asp:CheckBox ID="InactiveCheckBox" runat="server" 
                                    Checked='<%# DataBinder.Eval(Container.DataItem, "inactive") %>' Enabled="False" />
                            </ItemTemplate>
                            <EditItemTemplate>
                                <asp:CheckBox ID="edit_InactiveCheckBox" Runat="server" 
                                    Checked='<%# Databinder.Eval(Container.DataItem, "inactive") %>' Enabled="True" />
                            </EditItemTemplate>

                            <ItemStyle Width="20px"></ItemStyle>
                        </asp:TemplateField>
                       
                       <asp:TemplateField HeaderText="Lst Mod Dt" ItemStyle-Width="150px" Visible="false">
                          <ItemTemplate>
                              <asp:Label id="moddate" runat="server" Text='<%# DataBinder.Eval(Container, "DataItem.modification_date") %>' > 
                              </asp:Label>
                         </ItemTemplate>

                         <ItemStyle Width="150px"></ItemStyle>
                       </asp:TemplateField>
                        
                     </Columns>
                </asp:GridView>
            </td>
            <td style="vertical-align:top;">
                <div class="frame">
                    <table class="font8veranda">
                        <tr>
                            <td colspan="2" class="font10veranda">
                                Add a New Location:</td>
                        </tr>
                        <tr>
                            <td class="aligntext">
                                <strong>Location ID: </strong>
                            </td>
                            <td>
                                <asp:TextBox ID="location_id" runat="server" AutoPostBack="false" MaxLength="10" 
                                    ReadOnly="false" CssClass="requiredfield" 
                                    TabIndex="1" ToolTip="Enter a unique Location ID." Width="50"></asp:TextBox>
                            </td>
                        </tr>
                        <tr>
                            <td class="aligntext">
                                <strong>Location Name: </strong>
                            </td>
                            <td>
                                <asp:TextBox ID="location_name" runat="server" AutoPostBack="false" MaxLength="100" 
                                    ReadOnly="false" 
                                    CssClass="requiredfield"  
                                    TabIndex="2" ToolTip="Enter the Location Name." Width="200"></asp:TextBox>
                            </td>
                        </tr>
 
                         <tr>
                            <td class="aligntext">
                                <strong>Inactive: </strong>
                            </td>
                            <td>
                                <asp:CheckBox ID="inactive" runat="server" AutoPostBack="false" Enabled="true" 
                                    TabIndex="8" ToolTip="Enter the status of the Location." />
                            </td>
                        </tr>
                         <tr>
                            <td>
                            </td>
                            <td class="buttonArea">
                                <asp:Button ID="btnAdd" runat="server" OnClick="AddLocation_Click" TabIndex="11" Text="Add" ToolTip="Click to save the Location. ALT+D" AccessKey="D"/>
                                    <div class="divider"/>
                                <asp:Button ID="btnClear" runat="server" OnClick="PageReset_Click" TabIndex="12" Text="Clear" UseSubmitBehavior="false" ToolTip="Click to reset the window. ALT+C" AccessKey="C"/>
                            </td>
                        </tr>
                        <tr>
                            <td style="text-align:Center;" colspan="2" class="paddingtop15">
                                <span id="AddMessage" runat="server" enableviewstate="false" class="font11arial"></span>
                            </td>
                        </tr>
                    </table>
                </div>
            </td>
        </tr>
 
    </table>
 
         <div class="buttonArea">
                 <asp:Button ID="btnPrint" Font-Size="Large" runat="server" OnClick="PrintData" TabIndex="13" Text="Print" ToolTip="Click to Print the Data. ALT+P" AccessKey="P"/>
                <asp:Button ID="btnReturn" Font-Size="Large" runat="server" OnClick="ReturnToMainMenu" TabIndex="14" Text="Return to Main Menu" ToolTip="Click to return to the Web Security Main Menu. ALT+R" AccessKey="R" />
         </div>

         <div>
             <span id="Message" EnableViewState="false"  runat="server"/>
         </div>

        <table style="width:100%;" class="textalignright">
           <tr>
            <td>
                <asp:TextBox ID="sort_id" runat="server" AutoPostBack="false" MaxLength="40" 
                    ReadOnly="true" 
                    Visible="false" Width="40"></asp:TextBox>
            </td>
           </tr>
         </table>


         </div>
           </div>

  </form>

</body>
</html>
