<%@ Page Language="vb" AutoEventWireup="true" CodeBehind="wsusermastermaint.aspx.vb" Inherits="RexairWebSecurity.wsusermastermaint" EnableSessionState = "True"%>

<!--#include virtual="/ForceSSL.inc"-->

<!DOCTYPE HTML>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title>WS User Master Maintenance</title>
    <link rel="stylesheet" href="../Content/wsSite.css"/>
     <script src="../Scripts/JavaScript.js" type="text/javascript"></script>
</head>

<body oncontextmenu="return false">

 

  <form id="wsusermastermaint" runat="server">
      <div id="container">
          <div class="row">
               <div class="column left" > <h1>User Master Maintenance</h1>
               </div>
               <div class="column right" > <img src="../images/logo_small.png" alt="Rexair LLC"  width="200" height="100" />
               </div>
         </div>

        <div id="frame">
	
      <table class="table_input" >
        <tr>
            <td style="vertical-align:top;">
                 <asp:GridView ID="MyGridView" runat="server" 
                    Width="900"
                    AllowPaging="True" 
                    AllowSorting="True" 
                    AutoGenerateColumns="false" 
                    BackColor="#CCCCCC" 
                    BorderColor="black" 
                    CellPadding="3" 
                    CellSpacing="0" 
                    EnableViewState="true" 
                    Font-Names="Verdana" 
                    Font-Size="8pt" 
                    HeaderStyle-BackColor="#aaaadd" 
                    DataKeyNames="user_id"
			        AutoGenerateEditButton = "true"
			        AutoGenerateDeleteButton = "true" 
			        OnRowCancelingEdit = "gv_RowCancelingEdit" 
			        OnRowDeleting="gv_RowDeleting" 
			        OnRowDeleted="gv_RowDeleted"
			        OnRowUpdating="gv_RowUpdating" 
			        OnRowUpdated="gv_RowUpdated"
			        OnRowEditing="gv_RowEditing" 
			        OnPageIndexChanged = "gv_PageIndexChanged" 
			        OnPageIndexChanging = "gv_PageIndexChanging" 
			        OnRowDataBound = "gv_RowDataBound"
			        OnRowCreated = "gv_RowCreated"
			        OnSorting="gv_Sorting" 
			        OnPreRender="gv_PreRender"
			        PageSize="200" 
                    ShowFooter="false">
                    
		    <FooterStyle forecolor="Black" backcolor="#CCCCCC"></FooterStyle>
            <HeaderStyle font-bold="True" forecolor="White" backcolor="#2876CD"></HeaderStyle>
            <PagerStyle horizontalalign="Right" forecolor="Black" backcolor="#999999" 
                         Font-Names="Verdana" Font-Size="Small"></PagerStyle>
            <PagerSettings Mode="NumericFirstLast" Position="Top"/>
			<EditRowStyle BackColor="#E6E8FA" />
            <SelectedRowStyle BackColor="#C5BBAF" Font-Bold="True" ForeColor="#333333" />
            <EmptyDataTemplate>
               <asp:Label ID="Label1" runat="server">
                   There is no data to display in this view.
               </asp:Label>
            </EmptyDataTemplate>
            
                     <Columns>
                         <asp:BoundField DataField="user_id" HeaderText="User ID" 
                            ItemStyle-Width="100px" ReadOnly="true" SortExpression="user_id" HeaderStyle-HorizontalAlign="Left">
                          <ItemStyle Width="100px"></ItemStyle>
                         </asp:BoundField>

			            <asp:TemplateField HeaderText="User Name" HeaderStyle-HorizontalAlign="Left" ItemStyle-Width="200px" SortExpression="user_name">
                            <ItemTemplate>
                               <%#Eval("user_name")%>
                            </ItemTemplate> 
                            <EditItemTemplate>
                                <asp:TextBox ID="username" runat="server" Text='<%#Eval("user_name") %>'/>
                            </EditItemTemplate> 

                            <HeaderStyle HorizontalAlign="Left"></HeaderStyle>

                            <ItemStyle Width="200px"></ItemStyle>
                        </asp:TemplateField>                            
                            
                   		<asp:TemplateField HeaderText="Email" HeaderStyle-HorizontalAlign="Left" ItemStyle-Width="240px" SortExpression="user_email">
                            <ItemTemplate>
                               <%#Eval("user_email")%>
                            </ItemTemplate> 
                            <EditItemTemplate>
                               <asp:TextBox ID="useremail" runat="server" Text='<%#Eval("user_email") %>'/>
                            </EditItemTemplate> 

                            <HeaderStyle HorizontalAlign="Left"></HeaderStyle>

                            <ItemStyle Width="240px"></ItemStyle>
                       </asp:TemplateField>

                       <asp:TemplateField HeaderText="Cadillac Loc" ItemStyle-Width="20px" SortExpression="loc_cadiilac">
                            <ItemTemplate>
                                <asp:CheckBox ID="LocCadCheckBox" runat="server" 
                                    Checked='<%# DataBinder.Eval(Container.DataItem, "loc_cadillac") %>'  Enabled="False" />
                            </ItemTemplate>
                            <EditItemTemplate>
                                <asp:CheckBox ID="edit_LocCadCheckBox" Runat="server" 
                                    Checked='<%# DataBinder.Eval(Container.DataItem, "loc_cadillac") %>' Enabled="True" />
                            </EditItemTemplate>

                            <ItemStyle Width="20px"></ItemStyle>
                        </asp:TemplateField>

                        <asp:TemplateField HeaderText="Troy Loc" ItemStyle-Width="20px" SortExpression="loc_troy">
                            <ItemTemplate>
                                <asp:CheckBox ID="LocTroyCheckBox" runat="server" 
                                    Checked='<%# DataBinder.Eval(Container.DataItem, "loc_troy") %>'  Enabled="False" />
                            </ItemTemplate>
                            <EditItemTemplate>
                                <asp:CheckBox ID="edit_LocTroyCheckBox" Runat="server" 
                                    Checked='<%# DataBinder.Eval(Container.DataItem, "loc_troy") %>' Enabled="True" />
                            </EditItemTemplate>

                            <ItemStyle Width="20px"></ItemStyle>
                        </asp:TemplateField>
                         

                       <asp:TemplateField HeaderText="Inact" ItemStyle-Width="20px" SortExpression="inactive">
                            <ItemTemplate>
                                <asp:CheckBox ID="InactiveCheckBox" runat="server" 
                                    Checked='<%# DataBinder.Eval(Container.DataItem, "inactive") %>'  Enabled="False" />
                            </ItemTemplate>
                            <EditItemTemplate>
                                <asp:CheckBox ID="edit_InactiveCheckBox" Runat="server" 
                                    Checked='<%# Databinder.Eval(Container.DataItem, "inactive") %>' Enabled="True" />
                            </EditItemTemplate>

                            <ItemStyle Width="20px"></ItemStyle>
                        </asp:TemplateField>
                        
                        <asp:TemplateField HeaderText="Mstr" ItemStyle-Width="20px" SortExpression="master_account">
                            <ItemTemplate>
                                <asp:CheckBox ID="InactiveMCheckBox" runat="server" 
                                    Checked='<%# Databinder.Eval(Container.DataItem, "master_account") %>' Enabled="False" />
                            </ItemTemplate>
                            <EditItemTemplate>
                                <asp:CheckBox ID="edit_InactiveMCheckBox" Runat="server" 
                                    Checked='<%# Databinder.Eval(Container.DataItem, "master_account") %>' Enabled="True" />
                            </EditItemTemplate>

                            <ItemStyle Width="20px"></ItemStyle>
                        </asp:TemplateField>
                        
                        <asp:TemplateField HeaderText="NExp" ItemStyle-Width="20px" SortExpression="never_expire">
                            <ItemTemplate>
                                <asp:CheckBox ID="InactiveNECheckBox" runat="server" 
                                    Checked='<%# Databinder.Eval(Container.DataItem, "never_expire") %>' 
                                    Enabled="False" />
                            </ItemTemplate>
                            <EditItemTemplate>
                                <asp:CheckBox ID="edit_InactiveNECheckBox" Runat="server" 
                                    Checked='<%# Databinder.Eval(Container.DataItem, "never_expire") %>' 
                                    Enabled="True" />
                            </EditItemTemplate>

                            <ItemStyle Width="20px"></ItemStyle>
                        </asp:TemplateField>
                        
                       <asp:TemplateField HeaderText="Lst Mod Dt" ItemStyle-Width="150px" Visible="false">
                          <ItemTemplate>
                              <asp:Label id="moddate" runat="server" Text='<%# DataBinder.Eval(Container, "DataItem.modification_date") %>' > 
                              </asp:Label>
                         </ItemTemplate>

                         <ItemStyle Width="150px"></ItemStyle>
                       </asp:TemplateField>
                        
                     </Columns>
                </asp:GridView>
            </td>
            <td style="vertical-align:top;">
                <div class="frame">
                    <table class="font8veranda">
                        <tr>
                            <td colspan="2" class="font10veranda">
                                Add a New User:</td>
                        </tr>
                        <tr>
                            <td class="aligntext">
                                <strong>User ID: </strong>
                            </td>
                            <td>
                                <asp:TextBox ID="user_id" runat="server" AutoPostBack="false" MaxLength="50" 
                                    ReadOnly="false" CssClass="requiredfield" 
                                    TabIndex="1" ToolTip="Enter a unique User ID." Width="150"></asp:TextBox>
                            </td>
                        </tr>
                        <tr>
                            <td class="aligntext">
                                <strong>User Name: </strong>
                            </td>
                            <td>
                                <asp:TextBox ID="user_name" runat="server" AutoPostBack="false" MaxLength="100" 
                                    ReadOnly="false" 
                                    CssClass="requiredfield"  
                                    TabIndex="2" ToolTip="Enter the User Name." Width="200"></asp:TextBox>
                            </td>
                        </tr>

                        <tr>
                            <td class="aligntext">
                                <strong>Password: </strong>
                            </td>
                            <td>
                                <asp:TextBox ID="user_password" runat="server" maxlength="12"  CssClass="requiredfield"  tabindex="4" TextMode="password" ToolTip="Enter the User Password." 
                                    width="100" />
                            </td>
                        </tr>
                        <tr>
                            <td class="aligntext">
                                <strong>Verify Password: </strong>
                            </td>
                            <td>
                                <asp:TextBox ID="verify_password" runat="server" maxlength="12" CssClass="requiredfield"  tabindex="5" TextMode="password" ToolTip="Enter the Verification Password." 
                                    width="100" />
                            </td>
                        </tr>
                        <tr>
                            <td class="aligntext">
                                <strong>Email Acct: </strong>
                            </td>
                            <td>
                                <asp:TextBox ID="user_email" runat="server" maxlength="100" 
                                    CssClass="requiredfield" 
                                    tabindex="6" ToolTip="Enter the User Email Account." width="200" />
                            </td>
                        </tr>
                        <tr>
                            <td class="aligntext">
                                <strong>User Loc Cadillac: </strong>
                            </td>
                            <td>
                                <asp:CheckBox ID="loc_cadillac" runat="server" AutoPostBack="false" Enabled="true" 
                                    TabIndex="7" ToolTip="Check if the User is Physically located in Cadillac." />
                            </td>
                        </tr>
                        <tr>
                         <td class="aligntext">
                                <strong>User Loc Troy: </strong>
                            </td>
                            <td>
                                <asp:CheckBox ID="loc_troy" runat="server" AutoPostBack="false" Enabled="true" 
                                    TabIndex="8" ToolTip="Check if the User is Physically located in Troy." />
                            </td>
                        </tr>
                        <tr>
                            <td class="aligntext">
                                <strong>Master: </strong>
                            </td>
                            <td>
                                <asp:CheckBox ID="master_account" runat="server" AutoPostBack="false" 
                                    Enabled="true" TabIndex="9" 
                                    ToolTip="Check the box, if this is a Master User." />
                            </td>
                        </tr>
                        <tr>
                            <td class="aligntext">
                                <strong>Pass Never Expires: </strong>
                            </td>
                            <td>
                                <asp:CheckBox ID="never_expire" runat="server" AutoPostBack="false" Enabled="true" TabIndex="10" ToolTip="Check the box, if this is a Users Pass never expires." />
                            </td>
                        </tr>
                        <tr>
                            <td class="aligntext">
                                <strong>Inactive: </strong>
                            </td>
                            <td>
                                <asp:CheckBox ID="inactive" runat="server" AutoPostBack="false" Enabled="true" 
                                    TabIndex="11" ToolTip="Enter the status of the User." />
                            </td>
                        </tr>

                        <tr>
                            <td>
                            </td>
                            <td class="paddingtop15">
                                <asp:Button ID="btnAdd" runat="server" OnClick="AddUser_Click" TabIndex="12" Text="Add" ToolTip="Click to save the User. ALT+D" AccessKey="D"/>
                                 <div class="divider"/>
                                <asp:Button ID="btnClear" runat="server" OnClick="PageReset_Click" TabIndex="13" Text="Clear" ToolTip="Click to reset the window. ALT+C" AccessKey="C"/>
                            </td>
                        </tr>
                        <tr>
                            <td style="text-align:Center;" colspan="2" class="paddingtop15">
                                <span id="AddMessage" runat="server" enableviewstate="false" class="font11arial"></span>
                            </td>
                        </tr>
                    </table>
                </div>
            </td>
        </tr>
 
    </table>
 
         <div class="buttonArea">
                 <asp:Button ID="btnPrint" Font-Size="Large" runat="server" OnClientClick="openReportWin(); return false;" TabIndex="12" Text="Print" ToolTip="Click to Print the Data. ALT+P" AccessKey="P"/>
                <asp:Button ID="btnReturn" Font-Size="Large" runat="server" OnClientClick="closeReportWin(); return false;" TabIndex="13" Text="Return to Main Menu" ToolTip="Click to return to the Web Security Main Menu. ALT+R" AccessKey="R" />
         </div>

         <div>
             <span id="Message" EnableViewState="false"  runat="server"/>
         </div>

        <table style="width:100%;" class="textalignright">
           <tr>
            <td>
                <asp:TextBox ID="sort_id" runat="server" AutoPostBack="false" MaxLength="40" 
                    ReadOnly="true" 
                    Visible="false" Width="40"></asp:TextBox>
            </td>
           </tr>
         </table>


         </div>
           </div>

  </form>

</body>
</html>
